# build tests
build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    expire_in: 1 hour
    paths:
      - build

# run tests with the previously built executables
test:
  stage: test
  script:
    - cd build
    - ctest
