image: gcc

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake

build-debug:
  script:
    - "cmake -DCMAKE_BUILD_TYPE=Debug ."
    - "make"

build-release:
  script:
    - "cmake -DCMAKE_BUILD_TYPE=Release ."
    - "make"

test-debug:
  script:
    - "cmake -DCMAKE_BUILD_TYPE=Debug ."
    - "make"
    - "ls bin"
    - "./Test_BubbleSort"
    - "./Test_HeapSort"
    - "./Test_InsertionSort"
    - "./Test_MergeSort"

test-release:
  script:
    - "cmake -DCMAKE_BUILD_TYPE=Release ."
    - "make"
    - "ls bin"
    - "./Test_BubbleSort"
    - "./Test_HeapSort"
    - "./Test_InsertionSort"
    - "./Test_MergeSort"