# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

stages:
  - cmake
  - build
  - test

# create cmake caches
cmake:
    stage: cmake
    before_script:
     - apt update && apt -y install make cmake
    script:
     - cmake .

# build if cmake succeeded
build:
  stage: build
  script:
    - ls
    - make
  artifacts:
    paths:
      - bin

# run tests if build succeeded
test:
  stage: test
  script:
    - ./bin/Test_BubbleSort
    - ./bin/Test_HeapSort
    - ./bin/Test_InsertionSort
    - ./bin/Test_MergeSort
