image: gcc

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake

debug:
  script:
    - "cmake -DCMAKE_BUILD_TYPE=Debug ."
    - "make"

release:
  script:
    - "cmake -DCMAKE_BUILD_TYPE=Release ."
    - "make"

